# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=4.0.0
maven_group=tomyto.tomyslists
archives_base_name=tomys-lists

# Dependencies
fabric_api_version=0.159.0+26.2
owo_version=0.13.1+26.2
malilib_version=0.29.3
litematica_version=0.28.6
minecraft_version_out=26.2